---
- name: install build essentials
  become: true
  community.general.pacman:
    name: base-devel
    extra_args: --needed
  retries: 6

- name: clone yay git
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: ~/yay

- name: build yay
  shell: |
    cd ~/yay
    makepkg -si --noconfirm
    yay
