--- 
- name: install system
  hosts: localhost
  name: starting git roles
  pre_tasks:
    - name: update pacman
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
  roles:
    - { role: config, tags: config }
