---
- name: Enable tlp services
  systemd: 
    name: tlp.service
    state: started
    enabled: true
  become: yes

- name: Enable thermald services
  systemd: 
    name: thermald.service
    state: started
    enabled: true
  become: yes


- name: Enable cpupower service
  systemd: 
    name: cpupower.service
    state: started
    enabled: true
  become: yes


- name: Enable libvirtd service
  systemd: 
    name: libvirtd.service
    state: started
    enabled: true
  become: yes


- name: Enable libvirtd socket
  systemd: 
    name: libvirtd.socket
    state: started
    enabled: true
  become: yes

- name: disable videocam
  shell: echo "blacklist uvcvideo" > /etc/modprobe.d/disable_webcam.conf
  become: yes
