---
- name: Enable services
  import_tasks: enable.yml
  tags: enable-systemd

- name: Disable services
  import_tasks: disable.yml
  tags: disable-systemd

- name: Blacklist modules
  shell: |
    echo "blacklist snd_hda_codec_hdmi" >> /etc/modprobe.d/blacklist.conf
    echo "blacklist btusb" >> /etc/modprobe.d/blacklist.conf
    echo "blacklist bluetooth" >> /etc/modprobe.d/blacklist.conf
    echo "blacklist uvcvideo" >> /etc/modprobe.d/blacklist.conf
  become: yes
