---
# - name: clone waybar
#   git:
#     repo: https://github.com/Alexays/Waybar
#     dest: $HOME/waybar

- name: install dependencies
  become: True
  apt:
    name: [ 'clang-tidy' , 'gobject-introspection' , 'libdbusmenu-gtk3-dev' , 'libevdev-dev' , 'libfmt-dev' , 'libgirepository1.0-dev' , 'libgtk-3-dev' , 'libgtkmm-3.0-dev' , 'libinput-dev' , 'libjsoncpp-dev' , 'libmpdclient-dev' , 'libnl-3-dev' , 'libnl-genl-3-dev' , 'libpulse-dev' , 'libsigc++-2.0-dev' , 'libspdlog-dev' , 'libwayland-dev' , 'scdoc' , 'upower' , 'libxkbregistry-dev','cmake']

# - name: build waybar
#   become: True
#   shell: |
#     cd /home/{{ current_user }}/waybar
#     meson build
#     ninja -C build
#     ./build/waybar
#     ninja -C build install
#
#
#   
