---
- name: install tmux
  community.general.pacman:
    name: tmux
  become: True
  retries: 6
  tags: tmux
  

- name: install fzf
  community.general.pacman:
    name: fzf
  become: True
  retries: 6
  tags: fzf

- name: install picom
  community.general.pacman:
    name: picom
  retries: 6
  become: True
  tags: picom

- name: install i3
  community.general.pacman:
    name: ["i3-wm","i3blocks","i3lock","i3status"]
  retries: 6
  become: True
  tags: i3
    
 
- name: install dunst
  community.general.pacman:
    name: dunst
  retries: 6
  become: True
  tags: dunst

- name: install pipewire
  community.general.pacman:
    name: ["pipewire","pipewire-alsa","wireplumber","pipewire-pulse"]
  retries: 6
  become: True
  tags: audio

- name: install polybor
  import_tasks: polybar.yml
  tags: polybar

- name: install zsh-shell
  import_tasks: zsh.yml
  tags: zsh

- name: install zsh-defer
  import_tasks: zsh-defer.yml
  tags: zsh-defer

- name: install powerlevel10k theme
  import_tasks: powerlevel10k.yml
  tags: shelltheme

- name: install zsh suggestions
  import_tasks: git_suggestions.yml
  tags: suggestions-zsh
