- name: install picom
  apt:
    name: ['libconfig-dev', 'libdbus-1-dev', 'libegl-dev', 'libev-dev', 'libgl-dev', 'libpcre2-dev', 'libpixman-1-dev', 'libx11-xcb-dev', 'libxcb1-dev', 'libxcb-composite0-dev', 'libxcb-damage0-dev', 'libxcb-dpms0-dev', 'libxcb-glx0-dev', 'libxcb-image0-dev', 'libxcb-present-dev', 'libxcb-randr0-dev', 'libxcb-render0-dev', 'libxcb-render-util0-dev', 'libxcb-shape0-dev', 'libxcb-util-dev', 'libxcb-xfixes0-dev', 'libxext-dev', 'meson', 'ninja-build', 'uthash-dev',]
  become: yes
  ignore_errors: yes

- name: clone picom
  git:
    repo: https://github.com/yshui/picom
    dest: /home/{{ current_user }}/picom

- name: build picom
  become: yes
  shell: |
    cd /home/{{ current_user }}/picom
    git submodule update --init --recursive
    meson --buildtype=release . build
    ninja -C build
    ninja -C build install
