---
# - name: install polybar dependencies
#   become: True
#   apt:
#      name: ["cmake","cmake-data","pkg-config","python3-sphinx","python3-packaging","libuv1-dev","libcairo2-dev","libxcb1-dev","libxcb-util0-dev","libxcb-randr0-dev","libxcb-composite0-dev","python3-xcbgen","xcb-proto","libxcb-image0-dev","libxcb-ewmh-dev","libxcb-icccm4-dev","libxcb-xkb-dev","libxcb-xrm-dev","libxcb-cursor-dev","libasound2-dev","libpulse-dev","libjsoncpp-dev","libmpdclient-dev","libcurl4-openssl-dev","libnl-genl-3-dev"]
#   ignore_errors: yes
#   
# - name: clone git polybar
#   git:
#     repo: https://github.com/polybar/polybar
#     dest: $HOME/polybar
#     recursive: True
#
# - name: build polybar
#   become: True
#   shell: |
#     cd /home/{{ current_user }}/polybar
#     mkdir build
#     cd build
#     cmake ..
#     make -j$(nproc)
#     make install

- name: add udev rules 
  become: True
  shell: |
    touch /etc/udev/rules.d/backlight.rules
    echo "ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="radeon_bl0", RUN+="/bin/chgrp video /sys/class/backlight/radeon_bl0/brightness" >> /etc/udev/rules.d/backlight.rules
    echo "ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="radeon_bl0", RUN+="/bin/chmod g+w /sys/class/backlight/radeon_bl0/brightness" >> /etc/udev/rules.d/backlight.rules
    usermod -aG video {{ current_user }}
  tags: polybar_rules
