---
- name: install tmux dependencies
  become: True
  apt:
    name: ["libevent-dev" ,"ncurses-dev" ,"bison" ,"pkg-config" ,"automake" ,"autotools-dev"]
    update_cache: True
  ignore_errors: yes

- name: clone tmux
  git:
    repo: https://github.com/tmux/tmux.git
    dest: $HOME/tmux

- name: build tmux
  become: True
  shell: | 
    cd /home/{{ current_user }}/tmux
    sh autogen.sh
    ./configure
    make install
    cd /home/{{ current_user }}/
