---
- name: install system-softwares
  community.general.pacman:
    name: ["cmake","brightnessctl","vnstat","sysstat","cpupower" ]
  become: yes
  retries: 6
  tags: system-utility

- name: install multimedia-utility-videos
  community.general.pacman:
    name: ["mpv","ffmpeg","mediainfo","cheese","pavucontrol","vlc","imv","ffmpegthumbnailer","webp-pixbuf-loader"]
  become: yes
  retries: 6
  tags: media-utility-videos

- name: install multimedia-utility-images
  community.general.pacman:
    name: ["nitrogen","lxappearance","arandr","xwallpaper","kcolorchooser","feh","gimp","chafa"]
  become: yes
  retries: 6
  tags: media-utility-images

- name: install user-utilities
  community.general.pacman:
    name: ["tldr","htop","rofi","bat","tree","xautolock","qbittorrent","libqalculate","sddm","xdotool","git-delta"]
  become: yes
  retries: 6
  tags: user-utility

- name: install disk-utilities
  community.general.pacman:
    name: ["smartmontools","gsmartcontrol","testdisk","udiskie"]
  become: yes
  retries: 6
  tags: disk-utility

- name: install power-temp-utilities
  community.general.pacman:
    name: ["lm_sensors","psensor","acpi","tlp","tlp-rdw","powertop","thermald"]
  become: yes
  retries: 6
  tags: temp-power-utility


- name: install social networking software
  community.general.pacman:
    name: telegram-desktop
  become: yes
  retries: 6
  tags: social
      
- name: install network tools
  community.general.pacman:
    name: ["openssh","proxychains-ng","tor","torbrowser-launcher","nmap","whois","wireshark-qt","wireshark-cli"]
  become: yes
  retries: 6
  tags: net-tools
      

- name: xorg and friends
  become: true
  community.general.pacman:
    name: [  'pkgstats',  'gst-libav',  'jre8-openjdk', 'amd-ucode', 'xorg' , 'xterm' , 'perl-file-mimeinfo' , 'less' , 'coreutils' , "man-db" , "man-pages" ]
  tags: xorg-friends
  retries: 6

- name: install downgrade package from yay
  command: yay -S downgrade --noconfirm

- name: make user bin directory
  file:
    path: $HOME/usr/bin
    state: directory
  tags: delta

- name: update mandb
  command: mandb
  become: yes
  tags: update-man
