---
- name: remove iptable
  community.general.pacman:
    name: ["iptables"]
    state: removed
    force: true
  become: yes
  retries: 6
  tags: remove_iptables

- name: install virt-manager
  community.general.pacman:
    name: ["virt-manager","dnsmasq","dmidecode","iptables-nft"]
  become: yes
  retries: 6
  tags: virt

- name: install qemu
  community.general.pacman:
    name: ["qemu-full"]
  become: yes
  retries: 6
  tags: qemu

- name: Add to libvirt
  become: yes
  user:
    name: "{{ current_user }}"
    groups: libvirt
    append: true


- name: Add to libvirt
  become: yes
  user:
    name: "{{ current_user }}"
    groups: libvirt-qemu
    append: true
